# -*- coding: utf-8 -*-
"""CUSENSOR_API

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hJWqZTXNCvMRm08r-VEoWf_LXK_wFqOD

**CREATED BY THEWAVEWY (PIYOUNGGUL SUPARSORN)**

CODE นี้ใช้สำหรับดึงข้อมูลสถานีวัดมลพิษทั่วประเทศไทย และค่ามลพิษที่วัดได้ (PM2.5, PM10) ที่วัดได้จากข้อมูลของ [cusense.net](https://cusense.net/map) API

ข้อมูลที่ได้จะเป็นข้อมูลที่ได้ในแต่ละวัน โดยในงานนี้นิสิตใช้ข้อมูลของวันที่ 9 กรกฎาคม 2566 ถ้าผู้สนใจต้องการใช้ ก็จะได้ข้อมูลของเครื่องวัด ณ วันและเวลานั้นๆทันที

ข้อมูลที่ได้จะจัดเก็บอยู่ใน Local Memory ของ Google Colab ในรูป .csv

# **ข้อมูลของสถานีต่างๆ**

**Returns every station's information in the database**
"""

import requests

# Define the API endpoint URL
url1 = 'https://www.cusense.net:8082/api/v1/stationInfo/all'

# Define the headers
headers = {
    'Content-Type': 'application/json',
    'X-Gravitee-Api-Key': '7be9f42f-7e74-4822-972d-5c1e3e783c9d'
}

# Send a GET request to the API endpoint with the headers
response = requests.get(url1, headers=headers)

# Check the response status code
if response.status_code == 200:
    # Successful request
    all_station = response.json()
    print(all_station)
else:
    # Error handling
    print('Request failed with status code:', response.status_code)

all_station['cusensor/CU-01']

all_station.keys()

sen = list(all_station.keys())

Name = []
for i in sen:
  name = all_station[i]['name']
  Name.append(name)

Name

Lat = []
for i in sen:
  lat = all_station[i]['lat']
  Lat.append(lat)

Lon = []
for i in sen:
  lon = all_station[i]['lon']
  Lon.append(lon)

Prov = []
for i in sen:
  prov = all_station[i]['province']
  Prov.append(prov)

Prov

import csv

list1 = sen
list2 = Name
list3 = Lat
list4 = Lon
list5 = Prov

# Combine the lists into a single list of tuples
combined_lists = list(zip(list1, list2, list3,list4,list5))

# Define the filename for the CSV file
filename = 'Sensor.csv'

# Write the data to the CSV file
with open(filename, 'w',encoding='utf-8-sig', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Sensor', 'Name', 'Lat','Lon','Prov'])  # Write the header
    writer.writerows(combined_lists)  # Write the data rows

print(f"The data has been written to {filename}.")

"""# **ข้อมูลค่ามลพิษ**

**Get lastest 1 hour averaged data of all active stations.**
"""

url2 = 'https://www.cusense.net:8082/api/v1/sensorData/realtime/all'
headers = {
    'Content-Type': 'application/json',
    'X-Gravitee-Api-Key': '7be9f42f-7e74-4822-972d-5c1e3e783c9d'
}
response = requests.get(url2, headers=headers)
if response.status_code == 200:
    # Successful request
    realtime = response.json()
    print(realtime)

realtime

all_sensors = list(realtime.keys())
print('they are'+' '+str(len(all_sensors))+' '+'sensors.')

print(all_sensors)

PM25 = []
for i in all_sensors:
  PM = realtime[i]['data'][0]['pm25']
  PM25.append(PM)

Time = []
for i in all_sensors:
  time = realtime[i]['data'][0]['time']
  Time.append(time)

PM10 = []
for i in all_sensors:
  PM = realtime[i]['data'][0]['pm10']
  PM10.append(PM)

Temp = []
for i in all_sensors:
  temp = realtime[i]['data'][0]['temp']
  Temp.append(temp)

Hum = []
for i in all_sensors:
  hum = realtime[i]['data'][0]['humid']
  Hum.append(hum)

"""*   **sensor** อยู่ใน list ชื่อ **all_sensors**
*   **time** อยู่ใน list ชื่อ **Time**
*   **pm 2.5** อยู่ใน list ชื่อ **PM25**
*   **pm 10** อยู่ใน list ชื่อ **PM10**
*   **temp** อยู่ใน list ชื่อ **Temp**
*   **humid** อยู่ใน list ชื่อ **Hum**

**จัดเก็บทุกอย่างเป็น csv**
"""

import csv

list1 = all_sensors
list2 = Time
list3 = PM25
list4 = PM10
list5 = Temp
list6 = Hum

# Combine the lists into a single list of tuples
combined_lists = list(zip(list1, list2, list3,list4,list5,list6))

# Define the filename for the CSV file
filename = 'PM.csv'

# Write the data to the CSV file
with open(filename, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Sensor', 'Time', 'PM2.5','PM10','Temp','Humid'])  # Write the header
    writer.writerows(combined_lists)  # Write the data rows

print(f"The data has been written to {filename}.")